name: Bot Log
on:
  schedule:
    - cron: '0 20 * * *'
  push:
  workflow_dispatch:
jobs:
  log:
    if: github.repository == 'Leizhenpeng/simen-website-seo-push'
    runs-on: Ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Setup Git Configuration
      run: |
        git config --global user.email "${{ secrets.BOT_EMAIL || 'action@github.com' }}"
        git config --global user.name "${{ secrets.BOT_NAME || 'GitHub Action' }}"
        
    - name: Setup Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
        
    - name: Build
      env:
        BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: |
        if [ -d "Workflow-Keep-Alive" ]; then
          cd Workflow-Keep-Alive
          sed -i "s/BOT_GITHUB_TOKEN/$BOT_GITHUB_TOKEN/g" ./main.py
          python main.py
        else
          echo "Workflow-Keep-Alive directory not found. Skipping this step."
        fi
        
    - name: Bot Log
      run: |
        mkdir -p botlog
        cd botlog
        Date=`date -d '+0 hours' +'%Y-%m-%d %H:%M:%S'`
        echo "[$Date] Successful" >> readme.md
        
    - name: Deploy to botlog branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./botlog
        publish_branch: botlog
